- name: Copy TLS certificates to the target hosts
  copy:
    src: "{{druid_tls_cert}}"
    dest: "{{druid_host_tls_cert_path}}"
  when: druid_tls

- name: Copy TLS key to the target hosts.
  copy:
    src: "{{druid_tls_key}}"
    dest: "{{druid_host_tls_key_path}}"
  when: druid_tls

- name: Create keystore from the TLS cert and key
  shell: |
    openssl pkcs12 -export -in "{{druid_host_tls_cert_path}}" -inkey "{{druid_host_tls_key_path}}" -out /tmp/keystore.p12 -name "druid" -passout "pass:{{druid_keystore_password}}"
    keytool -importkeystore -srcstorepass "{{druid_keystore_password}}" -srckeystore /tmp/keystore.p12 -srcstoretype pkcs12 -destkeystore "{{druid_keystore_path}}" -storepass "{{druid_keystore_password}}"
  args:
    creates: "{{druid_keystore_path}}"
  when: druid_tls

- name: Create truststore from the TLS certificate
  shell: keytool -noprompt -import -alias druid -file "{{druid_host_tls_cert_path}}" -keystore "{{druid_truststore_path}}" -storepass "{{druid_keystore_password}}"
  args:
    creates: "{{druid_truststore_path}}"
  when: druid_tls
